### ISSUE TITLE
Logo For Pullable Sheet

### ISSUE THREAD

**Issue by zularizal** [tattn/PullableSheet#5]
Hi @tattn , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by tattn** [comment]
Wow, is it free?

Thank you for your proposal! I really appreciate it.
I am looking forward to it 😄

**Comment by zularizal** [comment]
Hi @tattn , sorry for a long time, this is my design logo for your project. What do you think? What color do you like for this logo?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/57187182-af722300-6f15-11e9-8ea7-4dfdc15e8e4a.png)

**Comment by tattn** [comment]
@zularizal  It's a great design! I want to use it 😄 
I prefer a yellow one.

Could you create a pull request?
Please put .png and .svg images in `docs/assets` directory for README.

**Comment by zularizal** [comment]
Hi @tattn , I sent a pull request. #6 

And also I have uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=1e52zVH8Ib-J7g4MpgEarArEV90TS4otZ

**Comment by tattn** [comment]
Thank you so much 😃 
I merged it! I appreciate your great work.
